create database customer_behaviour;
use customer_behaviour;
select * from updated_customer_shopping_behavior limit 20;

# Q1 what are the total revenue generated by male vs. female customers?
select gender,SUM(purchase_amount) as revenue
from updated_customer_shopping_behavior
group by gender;

# Q2 which customer used discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from updated_customer_shopping_behavior
where discount_applied= "Yes" and purchase_amount >= (select avg(purchase_amount) from updated_customer_shopping_behavior);

# Q3 which are the top 5 products with the highest average review rating 
select	item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from updated_customer_shopping_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5;
# Q4 Compare the average purchase amount between standard and express shipping?
select shipping_type, round(avg(purchase_amount),2)
from updated_customer_shopping_behavior
where shipping_type in ("Standard","Express")
group by shipping_type;

#Q5 do subscribers spent more? compare average spent and total revenue between subscribers and non subscribers?
select subscription_status,count(customer_id) as "Total Customers", round(avg(purchase_amount),2) as "Average spend",round(sum(purchase_amount),2) as "Total revenue"
from updated_customer_shopping_behavior
group by subscription_status
order by "Average spend","Total revenue" desc;

#Q6 which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(100 * sum(case when discount_applied= "Yes" then 1 else 0 end)/count(*),2) as discount_rate
from updated_customer_shopping_behavior
group by item_purchased
order by discount_rate desc
limit 5;

#Q7 segment customers into new, returning and loyal based on there total number of previous purchases and show the count of each segment 
with customer_type as (
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "returning"
    else "loyal"
    end as customer_segment
from updated_customer_shopping_behavior
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

#Q8 what are the top 3 most purchased product with each category
WITH items_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM updated_customer_shopping_behavior
    GROUP BY category, item_purchased
)
SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM items_count
WHERE item_rank <= 3;

#Q9 are customers who are the repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from updated_customer_shopping_behavior
where previous_purchases > 5
group by subscription_status;

#Q10 what is the revenue contribution of each age group
select age_group,
sum(purchase_amount) as Total_Revenue
from updated_customer_shopping_behavior
group by age_group
order by Total_Revenue desc




